---
language: node_js
node_js:
  - node
env:
  global:
    - NODE_ENV=test
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - script: npm run start.ci coverage.ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks: https://coveralls.io/webhook
